# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5156996a189b4337b4f41d550a178b163a00d423e794464265c13690998998c69e05812bae467d5e26d843896854d6a3b2362d073180454ca260443ef95984e

test:
  secret_key_base: d7370baa0728fcf9dfae30031403df11d0f27f587ed35383346ec7122a48f52f3c48fbe2ca0361d6ca7e8beae4fd8cfec1c4c1328dcf3a076e017b1b230bb1a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
